import { createWhatsAppUrl, itemMessage } from './whatsapp.mjs';
export const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';
const whatsapp = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M20.5 11.7a8.5 8.5 0 0 1-12.6 7.5L3 20.5l1.3-4.7A8.5 8.5 0 1 1 20.5 11.7Z"/><path d="M8.2 7.5c-.7.2-1 1.1-.7 2.3.6 2.5 3.2 5 5.8 5.6 1.2.3 2-.2 2.2-.9l.3-1.1-2.5-1.1-.9 1a7.5 7.5 0 0 1-3.2-3.1l.9-1-1-2.1Z"/></svg>';
export const cta = (id, x, classes='text-link', itemId='') => `<a class="${classes}" href="${esc(createWhatsAppUrl(x.message))}" target="_blank" rel="noopener noreferrer" data-cta-id="${esc(id)}" data-section="${esc(x.section)}"${itemId?` data-item-id="${esc(itemId)}"`:''}${id==='floating'?' aria-label="Conversar com Camilla no WhatsApp"':''}>${id==='floating'?whatsapp:esc(x.label)+arrow}</a>`;
export function brand(site, home='', prefix='./', variant='color') {return `<a class="brand brand--${variant}" href="${home}#inicio" aria-label="${esc(site.name)}, início"><img src="${prefix}assets/brand/logo-horizontal-${variant}.png" width="972" height="206" alt="${esc(site.name)}, ${esc(site.signature)}"></a>`;}
export const groups = {
 properties:{label:'Imóveis',slug:'imoveis',cta:'Tenho interesse neste imóvel'},
 projects:{label:'Projetos',slug:'projetos',cta:'Quero conversar sobre um projeto semelhante'},
 articles:{label:'Conteúdo',slug:'conteudo',cta:'Quero aplicar essas orientações à minha busca'}
};
const criterionGuides = [
 {id:'planta-e-circulacao',number:'01',title:'Leitura da planta e circulação',summary:'Entenda percursos, proporções e conflitos antes de decidir.'},
 {id:'luz-e-ambientes',number:'02',title:'Relação entre luz e uso dos ambientes',summary:'Observe orientação solar, ventilação e conforto ao longo do dia.'},
 {id:'materiais-e-adaptacoes',number:'03',title:'Materiais e possibilidades de adaptação',summary:'Separe acabamento, conservação e limites técnicos de intervenção.'},
 {id:'imovel-e-rotina',number:'04',title:'Compatibilidade com a rotina',summary:'Relacione ambientes, hábitos e mudanças previsíveis de uso.'}
];
export function layout({site,ctas,collections,body,title,description,canonical='',prefix='./',home=''}) {
 const optionalNav=Object.entries(groups).filter(([k])=>collections[k].length).map(([k,g])=>`<a href="${home}#${g.slug}">${g.label}</a>`).join('');
 const canonicalTags=canonical?`<link rel="canonical" href="${esc(canonical)}"><meta property="og:url" content="${esc(canonical)}"><meta property="og:image" content="${esc(new URL('assets/images/social-preview.jpg',site.siteUrl+'/').href)}"><meta property="og:image:width" content="863"><meta property="og:image:height" content="872"><meta property="og:image:alt" content="Camilla Bonifácio, Arquitetura + Curadoria Imobiliária">`:'';
 return `<!doctype html><html lang="pt-BR" class="no-js" data-analytics="${site.analytics.enabled===true}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#F6EFE6"><meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}">${canonicalTags}<link rel="icon" type="image/png" href="${prefix}assets/brand/favicon.png"><link rel="preload" href="${prefix}assets/fonts/cormorant-400.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="${prefix}assets/fonts/montserrat-400.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${prefix}styles.css"><script>document.documentElement.classList.replace('no-js','js');</script><script src="${prefix}app.js" defer></script></head><body><a class="skip" href="#conteudo-principal">Pular para o conteúdo</a><header class="site-header"><div class="container header-inner">${brand(site,home,prefix)}<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="navigation" aria-label="Abrir menu"><span>Menu</span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3" aria-hidden="true"><path d="M3 7h18M3 12h18M3 17h18"/></svg></button><nav class="nav" id="navigation" aria-label="Navegação principal"><a href="${home}#inicio">Início</a><a href="${home}#sobre">Sobre</a><a href="${home}#servicos">Serviços</a>${optionalNav}<a href="${home}#contato">Contato</a>${cta('header',ctas.header,'button')}</nav></div></header><main id="conteudo-principal">${body}</main><footer class="footer"><div class="container footer-inner">${brand(site,home,prefix,'dark')}<p class="credit">Desenvolvido por ${esc(site.credit.name)}${site.credit.handle&&site.credit.url?` <a href="${esc(site.credit.url)}" target="_blank" rel="noopener noreferrer" aria-label="Instagram de ${esc(site.credit.name)}">${esc(site.credit.handle)}</a>`:''}</p></div></footer>${cta('floating',ctas.floating,'floating')}</body></html>`;
}
export function homeBody({site,ctas,services,collections}) {
return `<section class="container hero" id="inicio" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow">${esc(site.signature)}</p><h1 id="hero-title">Uma arquiteta ajudando você a escolher melhor o imóvel que vai <em>chamar de casa.</em></h1><p>Um olhar para a planta, os espaços e a sua rotina, com orientação para uma escolha mais consciente.</p><div class="hero-actions">${cta('hero',ctas.hero,'button')}<a class="text-link" href="#servicos">Conheça meu trabalho ${arrow}</a></div></div><div class="hero-visual"><figure class="hero-portrait"><img src="./assets/images/camilla-blazer-863.webp" srcset="./assets/images/camilla-blazer-480.webp 480w, ./assets/images/camilla-blazer-863.webp 863w" sizes="(max-width:600px) calc(100vw - 68px), (max-width:1240px) 37vw, 445px" width="863" height="872" alt="Camilla Bonifácio de blazer branco, em retrato circular." fetchpriority="high" decoding="async"></figure><div class="hero-manifesto" aria-label="Espaços, pessoas, histórias e escolhas que fazem sentido"><span>Espaços</span><span>Pessoas</span><span>Histórias</span><span>Escolhas</span><span>Que fazem sentido</span></div></div></section>
<section class="section about" id="sobre" aria-labelledby="about-title"><div class="container about-grid"><figure class="about-portrait"><img src="./assets/images/camilla-rosa-800.webp" srcset="./assets/images/camilla-rosa-480.webp 480w, ./assets/images/camilla-rosa-800.webp 800w" sizes="(max-width:600px) calc(100vw - 44px), 438px" width="800" height="1622" alt="Camilla Bonifácio sorrindo, com roupa rosa." loading="lazy" decoding="async"><figcaption class="caption">Camilla Bonifácio · Arquiteta e corretora de imóveis</figcaption></figure><div class="section-copy"><img class="about-mark" src="./assets/brand/monogram-light.png" width="355" height="333" alt="" loading="lazy"><p class="eyebrow">Sobre Camilla</p><h2 id="about-title">Arquitetura e curadoria para orientar sua escolha.</h2><p>Sou Camilla Bonifácio, arquiteta e corretora de imóveis. Meu olhar reúne a leitura dos espaços e a compreensão do que você procura para morar.</p><p>A proposta é ajudar você a observar além da metragem e entender como cada imóvel pode se encaixar na sua rotina e nos seus planos.</p>${cta('about',ctas.about)}</div></div></section>
<section class="section container" id="servicos" aria-labelledby="services-title"><div class="section-heading"><p class="eyebrow">Serviços</p><h2 id="services-title">Da escolha do imóvel ao planejamento dos espaços.</h2></div><div class="services-grid">${services.map((s,i)=>{const slug=s.id==='curadoria'?'curadoria-imobiliaria':s.id==='arquitetura'?'arquitetura-residencial':'consultoria-e-acompanhamento';return `<article class="service"><span class="service-number">0${i+1}</span><h3><a href="./servicos/${slug}/">${esc(s.name)}</a></h3><p>${esc(s.description)}</p><div class="service-links"><a class="detail-link" href="./servicos/${slug}/">Entenda como funciona ${arrow}</a>${cta('service-'+s.id,{label:s.cta,section:'servicos',message:s.message},'text-link',s.id)}</div></article>`;}).join('')}</div></section>
<section class="section difference" aria-labelledby="difference-title"><div class="container"><img class="difference-logo" src="./assets/brand/logo-horizontal-dark.png" width="972" height="206" alt="Camilla Bonifácio, Arquitetura + Curadoria Imobiliária" loading="lazy"><div class="difference-grid"><div><p class="eyebrow">Um olhar para além da metragem</p><h2 id="difference-title">O que o olhar de uma arquiteta acrescenta à escolha.</h2>${cta('difference',ctas.difference)}</div><ol class="criteria">${criterionGuides.map(x=>`<li><a href="./criterios/${x.id}/"><span>${x.number}</span><span class="criterion-copy"><strong>${esc(x.title)}</strong><small>${esc(x.summary)}</small></span>${arrow}</a></li>`).join('')}</ol></div></div></section>
${Object.entries(groups).filter(([k])=>collections[k].length).map(([k,g])=>`<section class="section collection container" id="${g.slug}"><div class="section-heading"><p class="eyebrow">${g.label}</p><h2>${g.label==='Conteúdo'?'Critérios para escolher melhor.':g.label}</h2></div><div class="collection-grid">${collections[k].map(item=>`<article class="collection-card"><a href="./${g.slug}/${esc(item.id)}/"><img src="./${esc(item.images[0].src)}" width="${item.images[0].width}" height="${item.images[0].height}" alt="${esc(item.images[0].alt)}" loading="lazy"><h3>${esc(item.title||item.name)}</h3></a>${item.location?`<p>${esc(item.location)}</p>`:''}${cta(`${k}-${item.id}`,{label:g.cta,section:g.slug,message:itemMessage(k,item)},'text-link',item.id)}</article>`).join('')}</div></section>`).join('')}
<section class="contact" id="contato" aria-labelledby="contact-title"><div class="container contact-inner"><img class="contact-logo" src="./assets/brand/logo-horizontal-light.png" width="972" height="206" alt="Camilla Bonifácio, Arquitetura + Curadoria Imobiliária" loading="lazy"><p class="eyebrow">Atendimento personalizado</p><h2 id="contact-title">Vamos conversar sobre o que você procura?</h2><p>Conte o que faz sentido para sua rotina e para o seu próximo imóvel.</p>${cta('contact',ctas.contact,'button button--light')}</div></section>`;
}
export function guideBody(guide) {
 const back=guide.kind==='service'?'servicos':'diferencial';
 return `<article class="guide"><header class="guide-hero"><div class="container guide-hero-grid"><div><a class="guide-back" href="../../#${back}">${arrow}<span>Voltar para ${guide.kind==='service'?'serviços':'os critérios'}</span></a><p class="eyebrow">${esc(guide.eyebrow)}</p><h1>${esc(guide.title)}</h1></div><p class="guide-intro">${esc(guide.intro)}</p></div></header><div class="container guide-layout"><div class="guide-content">${guide.sections.map((section,i)=>`<section class="guide-section"><span>0${i+1}</span><div><h2>${esc(section.title)}</h2><p>${esc(section.text)}</p></div></section>`).join('')}</div><aside class="guide-aside"><p class="eyebrow">Pontos para observar</p><ul>${guide.checklist.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>${cta('guide-'+guide.id,{label:guide.ctaLabel,section:guide.kind==='service'?'servicos':'criterios',message:guide.message},'button',guide.id)}</aside></div><section class="guide-sources"><div class="container"><p class="eyebrow">Referências consultadas</p><h2>Fontes para aprofundar.</h2><ul>${guide.sources.map(source=>`<li><a href="${esc(source.url)}" target="_blank" rel="noopener noreferrer">${esc(source.label)} ${arrow}</a></li>`).join('')}</ul><p class="source-note">Conteúdo informativo. A análise de cada imóvel depende de documentação, contexto e avaliação profissional específica.</p></div></section></article>`;
}
export function detailBody(type,item) {
 const g=groups[type];return `<article class="section container article-body"><a class="text-link back" href="../../#${g.slug}">Voltar para ${g.label.toLowerCase()}</a><p class="eyebrow">${g.label}${item.code?' · '+esc(item.code):''}</p><h1>${esc(item.title||item.name)}</h1>${item.location?`<p>${esc(item.location)}</p>`:''}${type==='projects'?`<p>Autoria: ${esc(item.author)}. ${esc(item.context)}</p>`:''}${item.images.map(im=>`<img class="detail-image" src="../../${esc(im.src)}" width="${im.width}" height="${im.height}" alt="${esc(im.alt)}" loading="lazy">`).join('')}${item.body.map(p=>`<p>${esc(p)}</p>`).join('')}${cta(`${type}-${item.id}`,{label:g.cta,section:g.slug,message:itemMessage(type,item)},'text-link',item.id)}</article>`;
}
